import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// README first (root package README.md), then autogenerate everything under docs/.
// The 'README' ID resolves to each plugin's own README.md since each plugin has its own path.
// dirName: 'docs' is relative to each plugin's path, so it resolves correctly per package.
const sidebars: SidebarsConfig = {
  defaultSidebar: [
    'README',
    { type: 'autogenerated', dirName: 'docs' },
  ],
};

export default sidebars;
